### ISSUE TITLE
error when trying to install with vundle

### ISSUE THREAD

**Issue by tfarina** [vim-jp/vim-go-extra#12]
Error detected while processing function <SNR>20_install_extras:
line    2:
E118: Too many arguments for function: globpath
E116: Invalid arguments for function join(globpath(gopath, 'src/' . v:val, 0, 1), ',')
Press ENTER or type command to continue

**Comment by crazymaster** [comment]
The fourth argument of globpath() was added on [Vim 7.4.279](https://github.com/vim-jp/vim/commit/9968a1d72525c095a72a3a4ebf4b0ab82212fae9).

**Comment by tfarina** [comment]
Thanks! I have upgrade to 7.4 today. I will try this later.

**Comment by mattn** [comment]
Sorry about delay, Just fixed this.
