### ISSUE TITLE
reduce "go env GOROOT" execution

### ISSUE THREAD

**Issue by koron** [vim-jp/vim-go-extra#16]
https://github.com/vim-jp/vim-go-extra/blob/522fc495fd9de46c3c87d46a81bff5b1072f5e97/autoload/go/complete.vim#L58-L65

パッケージ補完をする際に `goroot` を確定するために毎回 `go env GOROOT` を実行している。
せめて明示的に環境変数 `$GOROOT` が設定されている場合にはそちらを優先し、
`go env...` を実行しないようにするのはどうか?

減らすという意味では `goroot` をキャッシュすることも考えたが、
ちょっと良くない気がしたので、この提案内容とした。

**Comment by koron** [comment]
「それは良くない」ってのがあったら教えてもらえると嬉しいです。

なければ修正作ります。

**Comment by mattn** [comment]
GOPATH については途中で変更される可能性がありますが、GOROOT については無いです。

**Comment by koron** [comment]
結局、キャッシュすることにした。
キャッシュは `call go#env#cache_clear('root')` ではクリアできるので、
万が一 GOROOT変えたい場合も安心。

**Comment by koron** [comment]
done
